---

name: Deploy Scomp

on: 
  push: 
    branches: 
      - master

jobs:
  deploy-scomp: 
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master

      - name: npm install aws-sdk
        run: npm install aws-sdk

      - name: sync to s3
        run: aws s3 sync . s3://scomp.starwarsccg.org/ --exclude '.git/*' --exclude '.github/*' --exclude 'node_modules/*' --exclude README.md --exclude package-lock.json --exclude package.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}



